### ISSUE TITLE
I can't set it up!

### ISSUE THREAD

**Issue by nikipuh** [CasperReckless/cloudflare-dns-creator#1]
Can you give me a detailed installation tutorial?
Can it be hosted on a subdomain?

**Comment by CasperReckless** [comment]
Updated installation details. See README.md for more information if you're still interested in running this script. You will need to run this using your root domain connected to Cloudflare - subdomains are added to your root domain using this script. Feel free to e-mail me with any other questions (casper[at]mcpe.ga). Apologies for the delay.

**Comment by xBeastMode** [comment]
The service is currently being rewritten from scratch.
